# Generated by Django 6.0.2 on 2026-02-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="stock",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
